"""Compile a validated SearchJob into a data-only Lua module."""

from __future__ import annotations

from .job import SearchJob
from .profile import GameProfile


def _lua_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def render_lua_job(job: SearchJob, profile: GameProfile | None = None) -> str:
    if profile is not None and profile.id != job.profile_id:
        raise ValueError("job.profile_id does not match the supplied profile")
    game_version = profile.game_version if profile else "unknown"
    item_count = profile.item_count if profile and profile.item_count else 732
    seeds = list(job.candidates.iter_seed_strings())
    seed_lines = "\n".join(f"    {_lua_string(seed)}," for seed in seeds)
    return (
        "-- Generated by isaac-seed-seeker. Do not edit by hand.\n"
        "return {\n"
        "  schema_version = 1,\n"
        f"  id = {_lua_string(job.id)},\n"
        f"  profile_id = {_lua_string(job.profile_id)},\n"
        f"  game_version = {_lua_string(game_version)},\n"
        f"  item_count = {item_count},\n"
        f"  max_results = {job.max_results},\n"
        "  seeds = {\n"
        f"{seed_lines}\n"
        "  },\n"
        "}\n"
    )
