#!/usr/bin/env python3
"""Generate the constexpr Q3 rating lookup used by daily-good-v1."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "data" / "daily-good" / "q3-ratings.j460.json"
DEFAULT_CATALOG = ROOT / "data" / "catalog" / "eden-start-catalog.j460.json"
DEFAULT_OUTPUT = ROOT / "native" / "generated" / "daily_q3_ratings_j460.hpp"


def q3_catalog_keys(path: Path) -> set[str]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return {
        f"{entry['kind']}:{int(entry['search_id'])}"
        for entry in payload["entries"]
        if entry.get("variant") == "normal"
        and entry.get("kind") in {"active", "passive"}
        and entry.get("quality") == 3
        and entry.get("available_for_eden")
    }


def render_lookup(name: str, entries: list[tuple[int, int]]) -> list[str]:
    lines = [
        f"constexpr std::uint8_t {name}(std::int32_t id) noexcept {{",
        "    switch (id) {",
    ]
    lines.extend(f"        case {item_id}: return {rating};" for item_id, rating in entries)
    lines.extend(["        default: return 0;", "    }", "}", ""])
    return lines


def generate(input_path: Path, catalog_path: Path, output_path: Path) -> None:
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    ratings = payload["ratings"]
    expected = q3_catalog_keys(catalog_path)
    actual = set(ratings)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise ValueError(f"Q3 rating coverage mismatch; missing={missing}, extra={extra}")
    if any(type(score) is not int or score < 0 or score > 4 for score in ratings.values()):
        raise ValueError("every Q3 rating must be an integer from 0 to 4")

    grouped: dict[str, list[tuple[int, int]]] = {"active": [], "passive": []}
    for key, rating in ratings.items():
        kind, raw_id = key.split(":", 1)
        grouped[kind].append((int(raw_id), rating))
    for values in grouped.values():
        values.sort()

    lines = [
        "// Generated by scripts/generate-daily-q3-ratings.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace isaac_seed_seeker::generated {",
        "",
    ]
    lines.extend(render_lookup("daily_q3_active_rating", grouped["active"]))
    lines.extend(render_lookup("daily_q3_passive_rating", grouped["passive"]))
    lines.extend(
        [
            "constexpr std::int32_t daily_q3_rating_bonus(std::uint8_t rating) noexcept {",
            "    switch (rating) {",
            "        case 2: return 15;",
            "        case 3: return 30;",
            "        case 4: return 50;",
            "        default: return 0;",
            "    }",
            "}",
            "",
            "}  // namespace isaac_seed_seeker::generated",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    generate(arguments.input, arguments.catalog, arguments.output)
    print(arguments.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
