"""Generate the compact C++ default Profile from local extracted JSON snapshots."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "profiles" / "j460-full" / "proc.json"
TRINKETS = ROOT / "data" / "profiles" / "j460-full" / "trinket_pool.json"
OUTPUT = ROOT / "native" / "generated" / "builtin_profile_j460.cpp"
CATALOG_PROFILE = ROOT / "data" / "catalog" / "profile-j460.json"
CATALOG_LOCK = ROOT / "data" / "catalog" / "sources.lock.json"
CATALOG_SOURCE_DIR = ROOT / "data" / "catalog" / "sources"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def semantic_digest(value: object) -> str:
    canonical = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def boolean(value: bool) -> str:
    return "true" if value else "false"


def load_collectible_qualities() -> tuple[dict[int, int], dict[str, object]]:
    lock = json.loads(CATALOG_LOCK.read_text(encoding="utf-8"))
    item_source = next(source for source in lock["sources"] if source["key"] == "item")
    snapshot_path = (
        CATALOG_SOURCE_DIR
        / f"huiji-item.{item_source['revision']}.json"
    )
    snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
    for field in ("title", "revision", "timestamp", "sha1"):
        if snapshot["source"][field] != item_source[field]:
            raise ValueError(f"{snapshot_path}: {field} does not match sources.lock.json")

    document = snapshot["document"]
    fields = {
        field["name"]: index for index, field in enumerate(document["schema"]["fields"])
    }
    qualities: dict[int, int] = {}
    for row in document["data"]:
        if row[fields["type"]] != "道具":
            continue
        item_id = int(row[fields["id"]])
        quality = int(row[fields["quality"]])
        if quality < 0 or quality > 4:
            raise ValueError(f"collectible {item_id} has invalid quality {quality}")
        qualities[item_id] = quality
    return qualities, item_source


def write_catalog_profile(
    proc: dict[str, object],
    trinkets: dict[str, object],
    qualities: dict[int, int],
) -> None:
    """Publish the small Profile subset needed to build the offline name catalog."""

    collectible_entries = []
    for entry in proc["entries"]:
        if entry is None:
            continue
        item_id = int(entry["id"])
        blocked = bool(int(entry.get("flag47", 0)) & 1)
        collectible_entries.append(
            {
                "id": item_id,
                "kind": "active" if int(entry["type"]) == 3 else "passive",
                "quality": qualities[item_id],
                "available_for_eden": not blocked and item_id not in {43, 61, 235},
            }
        )

    trinket_entries = []
    for entry in trinkets["entries"]:
        trinket_entries.append(
            {
                "id": int(entry["raw"]) & 0x7FFF,
                "available_for_eden": bool(entry.get("flag4")) and bool(entry.get("flag5")),
            }
        )

    payload = {
        "schema_version": 1,
        "profile_id": "j460-full-unlock",
        "game_version": "v1.9.7.17.J460",
        "game_build": "J460",
        "source_sha256": {
            "proc_json": digest(PROC),
            "trinket_pool_json": digest(TRINKETS),
        },
        "collectibles": collectible_entries,
        "trinkets": trinket_entries,
    }
    CATALOG_PROFILE.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PROFILE.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    proc = json.loads(PROC.read_text(encoding="utf-8"))
    trinkets = json.loads(TRINKETS.read_text(encoding="utf-8"))
    qualities, quality_source = load_collectible_qualities()
    proc_ids = {int(entry["id"]) for entry in proc["entries"] if entry is not None}
    if proc_ids != qualities.keys():
        missing = sorted(proc_ids - qualities.keys())
        extra = sorted(qualities.keys() - proc_ids)
        raise ValueError(f"quality/Profile ID mismatch; missing={missing}, extra={extra}")
    lines = [
        '// Generated by scripts/generate-builtin-profile.py; do not edit by hand.',
        f"// Collectible qualities: {quality_source['title']} revision {quality_source['revision']} ({quality_source['sha1']}).",
        '#include "isaac_seed_seeker/builtin_profile.hpp"',
        "",
        "namespace isaac_seed_seeker {",
        "namespace {",
        "constexpr BuiltinProfileInfo profile_info{",
        '    "j460-full-unlock",',
        '    "v1.9.7.17.J460",',
        '    "J460",',
        f'    "{digest(PROC)}",',
        f'    "{digest(TRINKETS)}",',
        f'    "{semantic_digest({"entries": proc["entries"]})}",',
        f'    "{semantic_digest({"rngShr": trinkets.get("rngShr", 1), "rngShl": trinkets.get("rngShl", 5), "rngFin": trinkets.get("rngFin", 19), "entries": trinkets["entries"]})}",',
        "};",
        "}  // namespace",
        "",
        "const BuiltinProfileInfo& builtin_j460_profile_info() noexcept { return profile_info; }",
        "",
        "ProfileTables builtin_j460_profile() {",
        "    ProfileTables tables;",
        "    tables.collectibles = {",
    ]
    for entry in proc["entries"]:
        if entry is None:
            lines.append("        {0, true, false, false, 0},")
        else:
            blocked = bool(int(entry.get("flag47", 0)) & 1)
            active_slot = int(entry["type"]) == 3
            lines.append(
                f"        {{{int(entry['id'])}, {boolean(blocked)}, "
                f"{boolean(active_slot)}, true, {qualities[int(entry['id'])]}}},"
            )
    lines.extend(["    };", "    tables.trinkets = {"])
    for entry in trinkets["entries"]:
        base_id = int(entry["raw"]) & 0x7FFF
        available = bool(entry.get("flag4")) and bool(entry.get("flag5"))
        lines.append(f"        {{{base_id}, {boolean(available)}}},")
    lines.extend(
        [
            "    };",
            f"    tables.trinket_shift_right = {int(trinkets.get('rngShr', 1))};",
            f"    tables.trinket_shift_left = {int(trinkets.get('rngShl', 5))};",
            f"    tables.trinket_shift_final = {int(trinkets.get('rngFin', 19))};",
            "    return tables;",
            "}",
            "",
            "}  // namespace isaac_seed_seeker",
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    write_catalog_profile(proc, trinkets, qualities)


if __name__ == "__main__":
    main()
