"""Generate the compact C++ default Profile from local extracted JSON snapshots."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PROC = ROOT / "data" / "profiles" / "j460-full" / "proc.json"
TRINKETS = ROOT / "data" / "profiles" / "j460-full" / "trinket_pool.json"
OUTPUT = ROOT / "native" / "generated" / "builtin_profile_j460.cpp"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def semantic_digest(value: object) -> str:
    canonical = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def boolean(value: bool) -> str:
    return "true" if value else "false"


def main() -> None:
    proc = json.loads(PROC.read_text(encoding="utf-8"))
    trinkets = json.loads(TRINKETS.read_text(encoding="utf-8"))
    lines = [
        '// Generated by scripts/generate-builtin-profile.py; do not edit by hand.',
        '#include "isaac_seed_seeker/builtin_profile.hpp"',
        "",
        "namespace isaac_seed_seeker {",
        "namespace {",
        "constexpr BuiltinProfileInfo profile_info{",
        '    "j460-full-unlock",',
        '    "v1.9.7.17.J460",',
        '    "J460",',
        f'    "{digest(PROC)}",',
        f'    "{digest(TRINKETS)}",',
        f'    "{semantic_digest({"entries": proc["entries"]})}",',
        f'    "{semantic_digest({"rngShr": trinkets.get("rngShr", 1), "rngShl": trinkets.get("rngShl", 5), "rngFin": trinkets.get("rngFin", 19), "entries": trinkets["entries"]})}",',
        "};",
        "}  // namespace",
        "",
        "const BuiltinProfileInfo& builtin_j460_profile_info() noexcept { return profile_info; }",
        "",
        "ProfileTables builtin_j460_profile() {",
        "    ProfileTables tables;",
        "    tables.collectibles = {",
    ]
    for entry in proc["entries"]:
        if entry is None:
            lines.append("        {0, true, false, false},")
        else:
            blocked = bool(int(entry.get("flag47", 0)) & 1)
            active_slot = int(entry["type"]) == 3
            lines.append(
                f"        {{{int(entry['id'])}, {boolean(blocked)}, "
                f"{boolean(active_slot)}, true}},"
            )
    lines.extend(["    };", "    tables.trinkets = {"])
    for entry in trinkets["entries"]:
        base_id = int(entry["raw"]) & 0x7FFF
        available = bool(entry.get("flag4")) and bool(entry.get("flag5"))
        lines.append(f"        {{{base_id}, {boolean(available)}}},")
    lines.extend(
        [
            "    };",
            f"    tables.trinket_shift_right = {int(trinkets.get('rngShr', 1))};",
            f"    tables.trinket_shift_left = {int(trinkets.get('rngShl', 5))};",
            f"    tables.trinket_shift_final = {int(trinkets.get('rngFin', 19))};",
            "    return tables;",
            "}",
            "",
            "}  // namespace isaac_seed_seeker",
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
