#pragma once

#define IDR_WEB_INDEX 101
#define IDR_WEB_STYLE 102
#define IDR_WEB_APP 103
#define IDR_ITEM_CATALOG 104
#define IDR_ISAAC_SANS_FONT 105
#define IDR_SEEKER_TITLE 106
#define IDR_LANA_PIXEL_FONT 107
#define IDR_WEB_TREATMENT 108
#define IDR_WEB_INSPECTOR 109
#define IDR_WEB_INSPECTOR_APP 110
#define IDR_WEB_DAILY_GOOD 111
#define IDR_WEB_DAILY_GOOD_APP 112
#define IDR_WEB_DAILY_BAD 113
